// <auto-generated />
using CadastroProdutos.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroProdutos.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260211122602_SeedProdutos")]
    partial class SeedProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CadastroProdutos.Entities.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 15,
                            Nome = "Notebook Dell Inspiron",
                            Preco = 3499.99m
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 50,
                            Nome = "Mouse Logitech MX Master",
                            Preco = 349.90m
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 30,
                            Nome = "Teclado Mecânico Keychron",
                            Preco = 599.00m
                        },
                        new
                        {
                            Id = 4,
                            Estoque = 12,
                            Nome = "Monitor LG 27 UltraWide",
                            Preco = 1899.00m
                        },
                        new
                        {
                            Id = 5,
                            Estoque = 25,
                            Nome = "Headset HyperX Cloud II",
                            Preco = 459.99m
                        },
                        new
                        {
                            Id = 6,
                            Estoque = 40,
                            Nome = "SSD Samsung 1TB",
                            Preco = 499.00m
                        },
                        new
                        {
                            Id = 7,
                            Estoque = 18,
                            Nome = "Webcam Logitech C920",
                            Preco = 389.90m
                        },
                        new
                        {
                            Id = 8,
                            Estoque = 8,
                            Nome = "Cadeira Gamer DT3 Sports",
                            Preco = 1299.00m
                        },
                        new
                        {
                            Id = 9,
                            Estoque = 10,
                            Nome = "Mesa Digitalizadora Wacom",
                            Preco = 899.00m
                        },
                        new
                        {
                            Id = 10,
                            Estoque = 35,
                            Nome = "Hub USB-C 7 em 1",
                            Preco = 199.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
